# Generated by Django 4.2.29 on 2026-03-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wellbeing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=70)),
                (
                    "burnout",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("charge", models.IntegerField(default=70)),
                ("trend", models.CharField(default="+0", max_length=10)),
                ("alerts", models.JSONField(blank=True, default=list)),
                ("team", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellbeing",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "wellbeing",
            },
        ),
    ]
