name = "scalyo-api"
main = "src/index.js"
compatibility_date = "2024-09-01"

[vars]
FRONTEND_URL = "https://scalyo.app"
APP_URL = "https://scalyo-api.stratimaagency.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "scalyo-db"
database_id = "79e02869-b288-4255-b654-95e74f601fe2"

# ========================
# PREPROD ENVIRONMENT
# ========================
[env.preprod]
name = "scalyo-api-preprod"

[env.preprod.vars]
FRONTEND_URL = "https://preprod.scalyo.pages.dev"
APP_URL = "https://scalyo-api-preprod.stratimaagency.workers.dev"

[[env.preprod.d1_databases]]
binding = "DB"
database_name = "scalyo-db-preprod"
database_id = "9bbf3835-af0c-4176-8060-954b2e4c3205"
