# Generated by Django 4.2.29 on 2026-03-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KpiData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=50)),
                ("kpis", models.JSONField(blank=True, default=dict)),
                ("goals", models.JSONField(blank=True, default=dict)),
                ("custom_kpis", models.JSONField(blank=True, default=list)),
                ("history", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_data",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI data",
                "verbose_name_plural": "KPI data",
                "unique_together": {("company", "period")},
            },
        ),
    ]
