# Generated by Django 4.2.29 on 2026-03-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
