# Generated by Django 4.2.29 on 2026-03-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="stripe_customer_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="subscription_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
